Add read method
gisce/powerp-backend-client pull request #8
Opened 2017-09-20 12:26 UTC by AdriNicolau

## Jobs Done
* Added a read method to read data.
* Added docstring to the method.

2017-09-28 09:31 UTC, ecarreras requested changes

2017-09-28 09:31 UTC, ecarreras commented on powerpbackend_client/powerpbackend.py
> +                                })
The params should go in the `url` not in the body as json. This is working?

2017-10-18 10:22 UTC, AdriNicolau commented
@ecarreras requested changed done!

2017-10-18 10:23 UTC, ecarreras approved these changes

2017-10-18 10:23 UTC, merged